export const APIURL = {
  LOGIN: 'users/login',
  RESEND_LOGIN_OTP: 'users/resend-login-otp',
  CAPTCHA: 'captcha',
  VERIFY_OTP: 'users/verifyotp',
  SUPER_ADMIN_EMAIL_SERVICE: 'super-admin/email-service',
  SUPER_ADMIN_SMS_SERVICE: 'super-admin/sms-service',
  SUPER_ADMIN_IP_WHITELIST: 'super-admin/ip-whitelist',
  PORTAL_USERS: 'portal-users',

  VEHICLE: 'vehicle',
  LASTVEHICLEDATA: 'lastvehicledata',
  DEPARTMENTS: 'department',
  PLANTS: 'plant',
  DRIVER: 'driver',
  PLAYBACK: 'playback-optimized',
  VEHICLE_ROUTE: 'vehicleRoute',
  VEHICLE_ROUTE_STOP: 'vehicleRouteStop_id',
  GEOFENCE: 'geofence',
  ASSIGNSEAT: 'assignSeat',
  EMERGENCY: 'alert',
  DASHBOARDEMERGENCY: 'emergency',
  EMPLOYEE: 'employe',
  ANNOUNCEMENT: 'announcement',
  ROUTECHANGEREQ: 'routeChange',
  FEEDBACK: 'feedback',
  PLANTINTIME: 'plantInTime',
  PUNCHLOGREPORT: 'punchlogreportv2',
  UPLOAD: 'upload',
  EMPONBOARD: 'emponboard',

  //DASHBOARD APIS
  TOTALCOUNT: 'dashboard/totalcount',
  TOTALONBOARDEMP: 'dashboardemp',
  DEPARTMENTANALYTICS: 'departmentanalytics',
  LATEARRIVAL: 'dashboardlatearrival',
  OVERSPEEDVIOLATION: 'speedviolation',
  DISTANCECOVER: 'vehicledistance',

  PUNCHINMULTITRACK: 'multitrackpunch',
};
